-- Active Students 
WITH ADDRESS AS (
SELECT rsc.STUDENT_ID, rc.LOGIN_ID, rc.EMAIL 
FROM REG_CONTACT rc 
INNER JOIN REG_STU_CONTACT rsc ON rsc.CONTACT_ID = rc.CONTACT_ID
WHERE rsc.CONTACT_TYPE = 'M'
)

SELECT a.LOGIN_ID, r.FIRST_NAME, r.LAST_NAME, r.GENDER
,r.GRADE, 'id' + RTRIM(r.STUDENT_ID) AS PASSWORD, r.BUILDING AS SCHOOL_CODE
,a.EMAIL

FROM REG r 
INNER JOIN ADDRESS a ON a.STUDENT_ID = r.STUDENT_ID
WHERE r.CURRENT_STATUS = 'A' 
AND r.GRADE IN ('06','07','08','09','10','11','12')