-- Active Students with district email
WITH ADDRESS AS (
SELECT rsc.STUDENT_ID, rc.CONTACT_ID, rc.LOGIN_ID, rc.EMAIL 
FROM REG_CONTACT rc 
INNER JOIN REG_STU_CONTACT rsc ON rsc.CONTACT_ID = rc.CONTACT_ID
WHERE rsc.CONTACT_TYPE = 'M'
AND (rc.EMAIL LIKE '%kalamazoopublicschools%' OR rc.EMAIL IS NULL)
)
SELECT RTRIM(r.STUDENT_ID) AS STUDENT_ID, a.CONTACT_ID
FROM REG r 
INNER JOIN ADDRESS a ON a.STUDENT_ID = r.STUDENT_ID
WHERE r.CURRENT_STATUS = 'A' 
--AND r.BUILDING < 505000 AND r.BUILDING <> '501947'
--AND r.GRADE NOT IN ('PA','PP','PD','0A','0P','0D','NB','KD','KA','KP')